=== benqczyo/javacode/xml/user.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.benqczyo.com/xml/Schema"
	targetNamespace="http://www.benqczyo.com/xml/Schema"
	elementFormDefault="qualified" 
	attributeFormDefault="unqualified"
>

	<xs:element name="user">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="uid" type="xs:string"/>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="password" type="xs:string"/>
				<xs:element name="email" type="xs:string"/>
				<xs:element name="address" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="userdb">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="user" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== benqczyo/javacode/xml/bin/user.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><userdb xmlns="http://www.benqczyo.com/xml/Schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.benqczyo.com/xml/Schema user.xsd">
	<user>
		<uid>10001</uid>
		<name>benjamin</name>
		<password>sorry</password>
		<email>test@benqczyo.com</email>
		<address>abcdeft</address>

		
	<nickname>ben</nickname><nickname>ben</nickname></user>

	<user>
		<uid>10002</uid>
		<name>jack</name>
		<password>sorry</password>
		<email>test@benqczyo.com</email>
		<address>abcdefg</address>
	</user>

</userdb>
